/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LatexAutocompletePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/suggest.ts
var import_obsidian = require("obsidian");

// src/mathContext.ts
function isInMathContext(editor, cursor) {
  if (isInLatexCodeBlock(editor, cursor))
    return true;
  const line = editor.getLine(cursor.line);
  const textBeforeCursor = line.substring(0, cursor.ch);
  let inDisplayMath = false;
  inDisplayMath = countDollarDollar(textBeforeCursor, inDisplayMath);
  if (inDisplayMath)
    return true;
  for (let i = cursor.line - 1; i >= Math.max(0, cursor.line - 50); i--) {
    const prevLine = editor.getLine(i);
    inDisplayMath = countDollarDollar(prevLine, inDisplayMath);
    if (inDisplayMath)
      return true;
  }
  const withoutDisplayMath = textBeforeCursor.replace(/\$\$/g, "  ");
  const dollarCount = (withoutDisplayMath.match(/\$/g) || []).length;
  if (dollarCount % 2 === 1)
    return true;
  return false;
}
function countDollarDollar(text, state) {
  let pos = 0;
  let inDisplayMath = state;
  while (pos < text.length) {
    if (text.substring(pos, pos + 2) === "$$") {
      inDisplayMath = !inDisplayMath;
      pos += 2;
    } else {
      pos += 1;
    }
  }
  return inDisplayMath;
}
function isInLatexCodeBlock(editor, cursor) {
  for (let i = cursor.line - 1; i >= Math.max(0, cursor.line - 50); i--) {
    const line = editor.getLine(i).trim();
    if (line.startsWith("```")) {
      const lang = line.substring(3).trim().toLowerCase();
      return lang === "latex" || lang === "tex" || lang === "math";
    }
  }
  return false;
}
function findMathZoneStart(editor, cursor) {
  for (let i = cursor.line - 1; i >= Math.max(0, cursor.line - 50); i--) {
    const line2 = editor.getLine(i).trim();
    if (line2.startsWith("```")) {
      const lang = line2.substring(3).trim().toLowerCase();
      if (lang === "latex" || lang === "tex" || lang === "math") {
        return { line: i + 1, ch: 0 };
      }
      return null;
    }
  }
  const line = editor.getLine(cursor.line);
  const textBeforeCursor = line.substring(0, cursor.ch);
  let inDisplayMath = false;
  inDisplayMath = countDollarDollar(textBeforeCursor, inDisplayMath);
  if (inDisplayMath) {
    let pos = 0;
    while (pos < textBeforeCursor.length) {
      if (textBeforeCursor.substring(pos, pos + 2) === "$$") {
        return { line: cursor.line, ch: pos + 2 };
      }
      pos++;
    }
    for (let i = cursor.line - 1; i >= Math.max(0, cursor.line - 50); i--) {
      const prevLine = editor.getLine(i);
      let p = 0;
      while (p < prevLine.length) {
        if (prevLine.substring(p, p + 2) === "$$") {
          return { line: i, ch: p + 2 };
        }
        p++;
      }
    }
  }
  const withoutDisplayMath = textBeforeCursor.replace(/\$\$/g, "  ");
  const lastDollar = withoutDisplayMath.lastIndexOf("$");
  if (lastDollar !== -1) {
    return { line: cursor.line, ch: lastDollar + 1 };
  }
  return { line: cursor.line, ch: 0 };
}

// data/chinese-keywords.json
var chinese_keywords_default = {
  \u52A0: ["sum", "plus"],
  \u51CF: ["minus", "pm"],
  \u4E58: ["times", "cdot"],
  \u9664: ["div", "frac"],
  \u5206: ["frac", "dfrac", "tfrac"],
  \u6BD4\u4F8B: ["propto"],
  \u7EA6\u7B49: ["approx", "simeq"],
  \u7B49\u4E8E: ["equiv"],
  \u4E0D\u7B49\u4E8E: ["neq", "ne"],
  \u5927\u4E8E: ["gt", "geq"],
  \u5C0F\u4E8E: ["lt", "leq"],
  \u5927: ["geq", "gg"],
  \u5C0F: ["leq", "ll"],
  \u6B63\u8D1F: ["pm"],
  \u8D1F\u6B63: ["mp"],
  \u5C5E\u4E8E: ["in"],
  \u4E0D\u5C5E\u4E8E: ["notin"],
  \u5305\u542B: ["subset", "subseteq"],
  \u5305\u542B\u4E8E: ["supset", "supseteq"],
  \u4EA4: ["cap"],
  \u5E76: ["cup"],
  \u7A7A: ["emptyset", "varnothing"],
  \u5168: ["forall"],
  \u5B58: ["exists"],
  \u4E0D\u5B58\u5728: ["nexists"],
  \u8865: ["setminus"],
  \u4E14: ["land"],
  \u6216: ["lor"],
  \u975E: ["neg", "lnot"],
  \u63A8: ["vdash"],
  \u771F: ["top"],
  \u5047: ["bot"],
  \u56E0\u6B64: ["therefore"],
  \u56E0\u4E3A: ["because"],
  \u963F\u5C14\u6CD5: ["alpha"],
  \u8D1D\u5854: ["beta"],
  \u4F3D\u9A6C: ["gamma"],
  \u5FB7\u5C14\u5854: ["delta"],
  \u827E\u666E\u897F\u9F99: ["epsilon"],
  \u6CFD\u5854: ["zeta"],
  \u4F0A\u5854: ["eta"],
  \u897F\u5854: ["theta"],
  \u7EA6\u5854: ["iota"],
  \u5361\u5E15: ["kappa"],
  \u62C9\u59C6\u8FBE: ["lambda"],
  \u7F2A: ["mu"],
  \u7EBD: ["nu"],
  \u514B\u897F: ["xi"],
  \u6D3E: ["pi"],
  \u67D4: ["rho"],
  \u897F\u683C\u739B: ["sigma"],
  \u5957: ["tau"],
  \u5B87\u666E\u897F\u9F99: ["upsilon"],
  \u6590: ["phi"],
  \u5361: ["chi"],
  \u666E\u8D5B: ["psi"],
  \u6B27\u7C73\u4F3D: ["omega"],
  phi: ["phi", "varphi"],
  \u5DE6: ["leftarrow", "Leftarrow"],
  \u53F3: ["rightarrow", "Rightarrow"],
  \u4E0A\u4E0B: ["uparrow", "downarrow"],
  \u53CC\u5411: ["leftrightarrow", "Leftrightarrow"],
  \u6620\u5C04: ["mapsto"],
  \u957F\u5DE6: ["longleftarrow"],
  \u957F\u53F3: ["longrightarrow"],
  \u957F\u53CC\u5411: ["longleftrightarrow"],
  \u79EF: ["int", "iint", "iiint"],
  \u6C42\u548C: ["sum"],
  \u6C42\u79EF: ["prod"],
  \u6781\u9650: ["lim"],
  \u504F: ["partial"],
  \u68AF\u5EA6: ["nabla"],
  \u65E0\u7A77: ["infty"],
  \u5BFC\u6570: ["prime"],
  \u4E0A\u6807: ["hat", "widehat"],
  \u4E0B\u6807: ["underline"],
  \u4E0A\u5212\u7EBF: ["overline"],
  \u4E0B\u5212\u7EBF: ["underline"],
  \u5411\u91CF: ["vec", "overrightarrow"],
  \u6CE2\u6D6A: ["tilde", "widetilde"],
  \u70B9: ["dot"],
  \u53CC\u70B9: ["ddot"],
  \u4E0A\u62EC\u53F7: ["overbrace"],
  \u4E0B\u62EC\u53F7: ["underbrace"],
  \u6B63\u5F26: ["sin"],
  \u4F59\u5F26: ["cos"],
  \u6B63\u5207: ["tan"],
  \u4F59\u5207: ["cot"],
  \u5BF9\u6570: ["log", "ln"],
  \u6307\u6570: ["exp"],
  \u6700\u5927: ["max"],
  \u6700\u5C0F: ["min"],
  \u4E0A\u786E\u754C: ["sup"],
  \u4E0B\u786E\u754C: ["inf"],
  \u884C\u5217\u5F0F: ["det"],
  \u7EF4: ["dim"],
  \u76F8\u4F3C: ["sim"],
  \u5782\u76F4: ["perp"],
  \u5E73\u884C: ["parallel", "mid"],
  \u7B49\u4EF7: ["equiv"],
  \u6A21: ["bmod", "pmod"],
  \u5DE6\u62EC: ["left"],
  \u53F3\u62EC: ["right"],
  \u5C16\u62EC\u53F7: ["langle", "rangle"],
  \u4E0A\u53D6\u6574: ["lceil", "rceil"],
  \u4E0B\u53D6\u6574: ["lfloor", "rfloor"],
  \u7EDD\u5BF9\u503C: ["lvert", "rvert"],
  \u7701\u7565: ["ldots", "cdots", "vdots", "ddots"],
  \u7A7A\u683C: ["quad", "qquad"],
  \u89D2\u5EA6: ["circ", "degree"],
  \u7EC4\u5408: ["binom"],
  \u77E9\u9635: ["begin"],
  \u5206\u6BB5: ["cases"],
  \u6587\u5B57: ["text", "mathrm"],
  \u7C97\u4F53: ["mathbf"],
  \u82B1\u4F53: ["mathcal"],
  \u7A7A\u5FC3: ["mathbb"],
  \u5E42: ["hat"],
  \u4E0A: ["hat", "widehat"],
  \u5E3D: ["hat", "widehat"]
};

// data/japanese-keywords.json
var japanese_keywords_default = {
  \u305F\u3057: ["sum", "plus"],
  \u3072\u304D: ["minus", "pm"],
  \u304B\u3051: ["times", "cdot"],
  \u308F\u308B: ["div", "frac"],
  \u3076\u3093\u3059\u3046: ["frac", "dfrac", "tfrac"],
  \u308F\u308A\u3042\u3044: ["propto"],
  \u306B\u308B\u3044: ["approx", "simeq"],
  \u3069\u3046\u3061: ["equiv"],
  \u3075\u3069\u3046: ["neq", "ne"],
  \u304A\u304A\u304D: ["gt", "geq"],
  \u3061\u3044\u3055: ["lt", "leq"],
  \u3060\u3044: ["geq", "gg"],
  \u3057\u3087\u3046: ["leq", "ll"],
  \u305B\u3044\u3075: ["pm"],
  \u3075\u304F\u305B\u3044: ["mp"],
  \u3057\u3087\u305E\u304F: ["in"],
  \u3075\u305E\u304F: ["notin"],
  \u307B\u3046\u304C\u304F: ["subset", "subseteq"],
  \u3075\u304F\u304C\u304F: ["supset", "supseteq"],
  \u3053\u3046: ["cap"],
  \u308F\u3057\u3085\u3046\u3054\u3046: ["cup"],
  \u304B\u3089: ["emptyset", "varnothing"],
  \u3059\u3079\u3066: ["forall"],
  \u305D\u3093\u3056\u3044: ["exists"],
  \u3075\u305D\u3093\u3056\u3044: ["nexists"],
  \u307B: ["setminus"],
  \u304B\u3064: ["land"],
  \u307E\u305F\u306F: ["lor"],
  \u3072\u3066\u3044: ["neg", "lnot"],
  \u3059\u3044\u308A: ["vdash"],
  \u3057\u3093: ["top"],
  \u304E: ["bot"],
  \u3086\u3048\u306B: ["therefore"],
  \u306A\u305C\u306A\u3089: ["because"],
  \u3042\u308B\u3075\u3041: ["alpha"],
  \u3079\u30FC\u305F: ["beta"],
  \u304C\u3093\u307E: ["gamma"],
  \u3067\u308B\u305F: ["delta"],
  \u3044\u3077\u3057\u308D\u3093: ["epsilon"],
  \u305C\u30FC\u305F: ["zeta"],
  \u3048\u305F: ["eta"],
  \u3057\u30FC\u305F: ["theta"],
  \u3044\u305F: ["iota"],
  \u304B\u3063\u3071: ["kappa"],
  \u3089\u3080\u3060: ["lambda"],
  \u307F\u3085\u30FC: ["mu"],
  \u306B\u3085\u30FC: ["nu"],
  \u304F\u3057\u30FC: ["xi"],
  \u3071\u3044: ["pi"],
  \u308D\u30FC: ["rho"],
  \u3057\u3050\u307E: ["sigma"],
  \u305F\u3046: ["tau"],
  \u3046\u3077\u3057\u308D\u3093: ["upsilon"],
  \u3075\u3041\u3044: ["phi", "varphi"],
  \u304B\u3044: ["chi"],
  \u3077\u3055\u3044: ["psi"],
  \u304A\u3081\u304C: ["omega"],
  \u3072\u3060\u308A: ["leftarrow", "Leftarrow"],
  \u307F\u304E: ["rightarrow", "Rightarrow"],
  \u3046\u3048\u3057\u305F: ["uparrow", "downarrow"],
  \u305D\u3046\u3054\u3046: ["leftrightarrow", "Leftrightarrow"],
  \u3057\u3083\u305D\u3046: ["mapsto"],
  \u306A\u304C\u3072\u3060\u308A: ["longleftarrow"],
  \u306A\u304C\u307F\u304E: ["longrightarrow"],
  \u305B\u304D\u3076\u3093: ["int", "iint", "iiint"],
  \u308F: ["sum"],
  \u305B\u304D: ["prod"],
  \u3052\u3093\u304B\u3044: ["lim"],
  \u3078\u3093\u3073\u3076\u3093: ["partial"],
  \u3053\u3046\u3070\u3044: ["nabla"],
  \u3080\u3052\u3093: ["infty"],
  \u3069\u3046\u3073\u3076\u3093: ["prime"],
  \u3061\u3087\u3046\u305B\u3093: ["hat", "widehat"],
  \u304B\u305B\u3093: ["underline"],
  \u3058\u3087\u3046\u305B\u3093: ["overline"],
  \u304B\u305B\u30932: ["underline"],
  \u3079\u304F\u3068\u308B: ["vec", "overrightarrow"],
  \u306A\u307F: ["tilde", "widetilde"],
  \u3066\u3093: ["dot"],
  \u305D\u3046\u3066\u3093: ["ddot"],
  \u3058\u3087\u3046\u304B\u3063\u3053: ["overbrace"],
  \u304B\u304B\u3063\u3053: ["underbrace"],
  \u3055\u3044\u3093: ["sin"],
  \u3053\u3055\u3044\u3093: ["cos"],
  \u305F\u3093\u3058\u3047\u3093\u3068: ["tan"],
  \u3053\u305F\u3093\u3058\u3047\u3093\u3068: ["cot"],
  \u305F\u3044\u3059\u3046: ["log", "ln"],
  \u3057\u3059\u3046: ["exp"],
  \u3055\u3044\u3060\u3044: ["max"],
  \u3055\u3044\u3057\u3087\u3046: ["min"],
  \u3058\u3087\u3046\u3051\u3063\u304B\u3044: ["sup"],
  \u304B\u3051\u3063\u304B\u3044: ["inf"],
  \u304E\u3087\u3046\u308C\u3064\u3057\u304D: ["det"],
  \u3058\u3052\u3093: ["dim"],
  \u305D\u3046\u3058: ["sim"],
  \u3059\u3044\u3061\u3087\u304F: ["perp"],
  \u3078\u3044\u3053\u3046: ["parallel", "mid"],
  \u3068\u3046\u304B: ["equiv"],
  \u3058\u3087\u3046\u3088: ["bmod", "pmod"],
  \u3072\u3060\u308A\u304C\u3063\u3053: ["left"],
  \u307F\u304E\u304C\u3063\u3053: ["right"],
  \u3068\u304C\u3063\u3053: ["langle", "rangle"],
  \u3058\u3087\u3046\u307E\u308B: ["lceil", "rceil"],
  \u3057\u305F\u307E\u308B: ["lfloor", "rfloor"],
  \u305C\u3063\u305F\u3044\u3061: ["lvert", "rvert"],
  \u308A\u3087\u3046\u3066\u3093: ["ldots", "cdots", "vdots", "ddots"],
  \u304F\u3046\u304B\u304F: ["quad", "qquad"],
  \u304B\u304F\u3069: ["circ", "degree"],
  \u304F\u307F\u3042\u308F: ["binom"],
  \u304E\u3087\u3046\u308C\u3064: ["begin"],
  \u3076\u3093\u304D: ["cases"],
  \u3082\u3058: ["text", "mathrm"],
  \u3053\u305F\u3044: ["mathbf"],
  \u304B\u3057\u3087: ["mathcal"],
  \u304F\u3046\u3057\u3093: ["mathbb"],
  \u307C\u3046: ["hat", "widehat"]
};

// data/korean-keywords.json
var korean_keywords_default = {
  \uD569: ["sum", "plus"],
  \uCC28: ["minus", "pm"],
  \uACF1: ["times", "cdot"],
  \uB098\uB217: ["div", "frac"],
  \uBD84\uC218: ["frac", "dfrac", "tfrac"],
  \uBE44\uB840: ["propto"],
  \uC720\uC0AC: ["approx", "simeq"],
  \uB3D9\uCE58: ["equiv"],
  \uBD80\uB4F1: ["neq", "ne"],
  \uD06C: ["gt", "geq"],
  \uC791: ["lt", "leq"],
  \uB300: ["geq", "gg"],
  \uC18C: ["leq", "ll"],
  \uC591\uC218: ["pm"],
  \uC74C\uC218: ["mp"],
  \uC18D: ["in"],
  \uBE44\uC18D: ["notin"],
  \uD3EC\uD568: ["subset", "subseteq"],
  \uC5ED\uD3EC\uD568: ["supset", "supseteq"],
  \uAD50: ["cap"],
  \uD569\uC9D1\uD569: ["cup"],
  \uACF5\uC9D1\uD569: ["emptyset", "varnothing"],
  \uBAA8\uB4E0: ["forall"],
  \uC874\uC7AC: ["exists"],
  \uBD80\uC874\uC7AC: ["nexists"],
  \uC5EC: ["setminus"],
  \uADF8\uB9AC\uACE0: ["land"],
  \uB610\uB294: ["lor"],
  \uBD80\uC815: ["neg", "lnot"],
  \uCD94\uB860: ["vdash"],
  \uCC38: ["top"],
  \uAC70\uC9D3: ["bot"],
  \uADF8\uB7EC\uBBC0\uB85C: ["therefore"],
  \uC65C\uB0D0\uD558\uBA74: ["because"],
  \uC54C\uD30C: ["alpha"],
  \uBCA0\uD0C0: ["beta"],
  \uAC10\uB9C8: ["gamma"],
  \uB378\uD0C0: ["delta"],
  \uC785\uC2E4\uB860: ["epsilon"],
  \uC81C\uD0C0: ["zeta"],
  \uC5D0\uD0C0: ["eta"],
  \uC138\uD0C0: ["theta"],
  \uC694\uD0C0: ["iota"],
  \uCE74\uD30C: ["kappa"],
  \uB78C\uB2E4: ["lambda"],
  \uBBA4: ["mu"],
  \uB274: ["nu"],
  \uD06C\uC138: ["xi"],
  \uD30C\uC774: ["pi"],
  \uB85C: ["rho"],
  \uC2DC\uADF8\uB9C8: ["sigma"],
  \uD0C0\uC6B0: ["tau"],
  \uC6C1\uC2E4\uB860: ["upsilon"],
  \uD30C\uC7742: ["phi", "varphi"],
  \uD0A4: ["chi"],
  \uD504\uC0AC\uC774: ["psi"],
  \uC624\uBA54\uAC00: ["omega"],
  \uC67C: ["leftarrow", "Leftarrow"],
  \uC624\uB978: ["rightarrow", "Rightarrow"],
  \uC704\uC544\uB798: ["uparrow", "downarrow"],
  \uC591\uBC29\uD5A5: ["leftrightarrow", "Leftrightarrow"],
  \uC0AC\uC0C1: ["mapsto"],
  \uAE34\uC67C: ["longleftarrow"],
  \uAE34\uC624\uB978: ["longrightarrow"],
  \uC801\uBD84: ["int", "iint", "iiint"],
  \uD569\uACC4: ["sum"],
  \uACF1\uD558\uAE30: ["prod"],
  \uADF9\uD55C: ["lim"],
  \uD3B8\uBBF8\uBD84: ["partial"],
  \uAE30\uC6B8\uAE30: ["nabla"],
  \uBB34\uD55C: ["infty"],
  \uBBF8\uBD84: ["prime"],
  \uBAA8\uC790: ["hat", "widehat"],
  \uBC11\uC904: ["underline"],
  \uC717\uC904: ["overline"],
  \uBCA1\uD130: ["vec", "overrightarrow"],
  \uBB3C\uACB0: ["tilde", "widetilde"],
  \uC810: ["dot"],
  \uC30D\uC810: ["ddot"],
  \uC704\uAD04\uD638: ["overbrace"],
  \uC544\uB798\uAD04\uD638: ["underbrace"],
  \uC0AC\uC778: ["sin"],
  \uCF54\uC0AC\uC778: ["cos"],
  \uD0C4\uC820\uD2B8: ["tan"],
  \uCF54\uD0C4\uC820\uD2B8: ["cot"],
  \uB85C\uADF8: ["log", "ln"],
  \uC9C0\uC218: ["exp"],
  \uCD5C\uB300: ["max"],
  \uCD5C\uC18C: ["min"],
  \uC0C1\uD55C: ["sup"],
  \uD558\uD55C: ["inf"],
  \uD589\uB82C\uC2DD: ["det"],
  \uCC28\uC6D0: ["dim"],
  \uC720\uC0AC2: ["sim"],
  \uC218\uC9C1: ["perp"],
  \uD3C9\uD589: ["parallel", "mid"],
  \uB3D9\uCE582: ["equiv"],
  \uB098\uBA38\uC9C0: ["bmod", "pmod"],
  \uC67C\uAD04\uD638: ["left"],
  \uC624\uB978\uAD04\uD638: ["right"],
  \uAEBE\uC1E0: ["langle", "rangle"],
  \uC62C\uB9BC: ["lceil", "rceil"],
  \uB0B4\uB9BC: ["lfloor", "rfloor"],
  \uC808\uB300\uAC12: ["lvert", "rvert"],
  \uC810\uB4E4: ["ldots", "cdots", "vdots", "ddots"],
  \uACF5\uBC31: ["quad", "qquad"],
  \uAC01\uB3C4: ["circ", "degree"],
  \uC870\uD569: ["binom"],
  \uD589\uB82C: ["begin"],
  \uACBD\uC6B0: ["cases"],
  \uAE00\uC790: ["text", "mathrm"],
  \uAD75\uAC8C: ["mathbf"],
  \uD544\uAE30\uCCB4: ["mathcal"],
  \uC18D\uAD75: ["mathbb"]
};

// data/raw-symbols.json
var raw_symbols_default = {
  \u5E42: ["^"],
  \u4E0A\u6807: ["^"],
  \u4E0B\u6807: ["_"],
  \u4E0B: ["_"]
};

// data/raw-symbols-ja.json
var raw_symbols_ja_default = {
  \u3058\u3087\u3046\u3072\u3087\u3046: ["^"],
  \u3046\u3048: ["^"],
  \u304B\u3072\u3087\u3046: ["_"],
  \u3057\u305F: ["_"]
};

// data/raw-symbols-ko.json
var raw_symbols_ko_default = {
  \uC704\uCCA8\uC790: ["^"],
  \uC544\uB798\uCCA8\uC790: ["_"]
};

// src/langRegistry.ts
var LANG_REGISTRY = [
  {
    tag: "zh",
    keywordMap: chinese_keywords_default,
    rawMap: raw_symbols_default,
    regex: /[一-鿿]/,
    charClass: "\\u4e00-\\u9fff"
  },
  {
    tag: "ja",
    keywordMap: japanese_keywords_default,
    rawMap: raw_symbols_ja_default,
    regex: /[぀-ゟ゠-ヿ]/,
    charClass: "\\u3040-\\u309f\\u30a0-\\u30ff"
  },
  {
    tag: "ko",
    keywordMap: korean_keywords_default,
    rawMap: raw_symbols_ko_default,
    regex: /[가-힯]/,
    charClass: "\\uac00-\\ud7af"
  }
];
function buildCombinedScriptClass() {
  const seen = /* @__PURE__ */ new Set();
  const parts = [];
  const cjk = "\\u4e00-\\u9fff";
  if (!seen.has(cjk)) {
    seen.add(cjk);
    parts.push(cjk);
  }
  for (const lang of LANG_REGISTRY) {
    if (!seen.has(lang.charClass)) {
      seen.add(lang.charClass);
      parts.push(lang.charClass);
    }
  }
  return parts.join("");
}
function detectScript(query) {
  for (const lang of LANG_REGISTRY) {
    if (lang.tag === "zh")
      continue;
    if (lang.regex.test(query))
      return lang;
  }
  for (const lang of LANG_REGISTRY) {
    if (lang.tag === "zh" && lang.regex.test(query))
      return lang;
  }
  return null;
}
function resolveDescription(cmd, lang, locale) {
  var _a;
  if (cmd.descriptions) {
    const tag = (_a = lang == null ? void 0 : lang.tag) != null ? _a : locale.split("-")[0];
    if (cmd.descriptions[tag])
      return cmd.descriptions[tag];
  }
  if (((lang == null ? void 0 : lang.tag) === "zh" || locale.startsWith("zh")) && cmd.descriptionZh) {
    return cmd.descriptionZh;
  }
  return "";
}

// src/matcher.ts
function matchByPrefix(query, commands, locale) {
  const lowerQuery = query.toLowerCase();
  return commands.filter((cmd) => cmd.command.toLowerCase().startsWith(lowerQuery)).map((cmd) => ({
    command: cmd.command,
    displayText: cmd.snippet.replace(/\$\d+/g, "\xB7"),
    description: cmd.description,
    localDescription: resolveDescription(cmd, null, locale),
    snippet: cmd.snippet,
    source: "prefix"
  }));
}
function matchByKeywords(query, keywordMap, commandMap, lang, locale) {
  const results = [];
  const seen = /* @__PURE__ */ new Set();
  const lookups = [];
  for (let len = query.length; len >= 1; len--) {
    lookups.push(query.substring(0, len));
  }
  for (const ch of query) {
    if (!lookups.includes(ch)) {
      lookups.push(ch);
    }
  }
  for (const key of lookups) {
    const cmdNames = keywordMap[key];
    if (!cmdNames)
      continue;
    for (const name of cmdNames) {
      if (seen.has(name))
        continue;
      seen.add(name);
      const cmd = commandMap.get(name);
      if (!cmd)
        continue;
      results.push({
        command: cmd.command,
        displayText: cmd.snippet.replace(/\$\d+/g, "\xB7"),
        description: cmd.description,
        localDescription: resolveDescription(cmd, lang, locale),
        snippet: cmd.snippet,
        source: "keyword"
      });
    }
  }
  return results;
}
function matchRawSymbols(query, rawMap) {
  const results = [];
  const seen = /* @__PURE__ */ new Set();
  const lookups = [];
  for (let len = query.length; len >= 1; len--) {
    lookups.push(query.substring(0, len));
  }
  for (const ch of query) {
    if (!lookups.includes(ch)) {
      lookups.push(ch);
    }
  }
  for (const key of lookups) {
    const inserts = rawMap[key];
    if (!inserts)
      continue;
    for (const insert of inserts) {
      if (seen.has(insert))
        continue;
      seen.add(insert);
      results.push({
        command: insert,
        displayText: insert,
        description: "",
        localDescription: key,
        snippet: insert,
        source: "raw",
        isRaw: true
      });
    }
  }
  return results;
}
function matchCustomMappings(query, customMappings, hasScript) {
  const results = [];
  const lowerQuery = query.toLowerCase();
  for (const mapping of customMappings) {
    const keywordHasScript = /[一-鿿぀-ゟ゠-ヿ가-힯]/.test(mapping.keyword);
    if (hasScript && keywordHasScript) {
      let matched = false;
      for (let len = query.length; len >= 1; len--) {
        if (query.substring(0, len) === mapping.keyword) {
          matched = true;
          break;
        }
      }
      if (matched) {
        results.push({
          command: mapping.snippet,
          displayText: mapping.snippet.replace(/\$\d+/g, "\xB7"),
          description: "",
          localDescription: mapping.keyword,
          snippet: mapping.snippet,
          source: "custom",
          isCustom: true
        });
      }
    } else if (!hasScript && !keywordHasScript) {
      if (mapping.keyword.toLowerCase().startsWith(lowerQuery)) {
        results.push({
          command: mapping.keyword,
          displayText: mapping.snippet.replace(/\$\d+/g, "\xB7"),
          description: "",
          localDescription: "",
          snippet: mapping.snippet,
          source: "custom",
          isCustom: true
        });
      }
    }
  }
  return results;
}
function matchSuggestions(query, commands, commandMap, langRegistry, customMappings, locale) {
  const detectedLang = detectScript(query);
  const hasScript = detectedLang !== null;
  let results;
  if (hasScript && detectedLang) {
    const keywordResults = matchByKeywords(query, detectedLang.keywordMap, commandMap, detectedLang, locale);
    const rawResults = matchRawSymbols(query, detectedLang.rawMap);
    const extraResults = [];
    if (detectedLang.tag === "zh" || detectedLang.tag === "ja") {
      const cjkLang = langRegistry.find(
        (l) => (l.tag === "zh" || l.tag === "ja") && l.tag !== detectedLang.tag
      );
      if (cjkLang) {
        extraResults.push(...matchByKeywords(query, cjkLang.keywordMap, commandMap, cjkLang, locale));
        extraResults.push(...matchRawSymbols(query, cjkLang.rawMap));
      }
    }
    const customResults = matchCustomMappings(query, customMappings, true);
    const seen = /* @__PURE__ */ new Set();
    const deduped = [];
    for (const r of [...rawResults, ...keywordResults, ...extraResults, ...customResults]) {
      const key = `${r.command}:${r.source}`;
      if (!seen.has(key)) {
        seen.add(key);
        deduped.push(r);
      }
    }
    results = deduped;
  } else {
    const prefixResults = matchByPrefix(query, commands, locale);
    const customResults = matchCustomMappings(query, customMappings, false);
    results = [...prefixResults, ...customResults];
  }
  return results;
}

// src/suggest.ts
var LatexSuggest = class extends import_obsidian.EditorSuggest {
  constructor(app, commands, langRegistry, getSettings) {
    super(app);
    this.commands = commands;
    this.langRegistry = langRegistry;
    this.getSettings = getSettings;
    this.commandMap = /* @__PURE__ */ new Map();
    for (const cmd of commands) {
      this.commandMap.set(cmd.command, cmd);
    }
    this.limit = 25;
    const scriptClass = buildCombinedScriptClass();
    this.triggerRegex = new RegExp(`^[a-zA-Z${scriptClass}]+$`);
    this.rawTriggerRegex = new RegExp(`[${scriptClass}]+$`);
  }
  onTrigger(cursor, editor, _file) {
    const line = editor.getLine(cursor.line);
    const textBeforeCursor = line.substring(0, cursor.ch);
    if (!isInMathContext(editor, cursor))
      return null;
    const lastBackslash = textBeforeCursor.lastIndexOf("\\");
    if (lastBackslash !== -1) {
      if (!(lastBackslash > 0 && textBeforeCursor[lastBackslash - 1] === "\\")) {
        const queryText2 = textBeforeCursor.substring(lastBackslash + 1);
        if (queryText2.length > 0 && this.triggerRegex.test(queryText2)) {
          return {
            start: { line: cursor.line, ch: lastBackslash },
            end: { line: cursor.line, ch: cursor.ch },
            query: queryText2
          };
        }
      }
    }
    const scriptMatch = textBeforeCursor.match(this.rawTriggerRegex);
    if (!scriptMatch)
      return null;
    const queryText = scriptMatch[0];
    const scriptStart = textBeforeCursor.length - queryText.length;
    return {
      start: { line: cursor.line, ch: scriptStart },
      end: { line: cursor.line, ch: cursor.ch },
      query: queryText
    };
  }
  getSuggestions(context) {
    var _a, _b, _c, _d;
    const settings = this.getSettings();
    const locale = (_c = (_b = (_a = window.moment) == null ? void 0 : _a.locale) == null ? void 0 : _b.call(_a)) != null ? _c : "en";
    const results = matchSuggestions(
      context.query,
      this.commands,
      this.commandMap,
      this.langRegistry,
      (_d = settings.customMappings) != null ? _d : [],
      locale
    );
    return results;
  }
  renderSuggestion(suggestion, el) {
    const container = el.createDiv({ cls: "latex-suggest-item" });
    if (suggestion.isCustom) {
      container.createEl("code", {
        cls: "latex-suggest-command",
        text: suggestion.displayText
      });
      if (suggestion.localDescription) {
        container.createSpan({
          cls: "latex-suggest-desc",
          text: suggestion.localDescription
        });
      }
      return;
    }
    container.createEl("code", {
      cls: "latex-suggest-command",
      text: "\\" + suggestion.displayText
    });
    const desc = suggestion.localDescription ? suggestion.localDescription + (suggestion.description ? " (" + suggestion.description + ")" : "") : suggestion.description;
    if (desc) {
      container.createSpan({
        cls: "latex-suggest-desc",
        text: desc
      });
    }
  }
  selectSuggestion(suggestion, _evt) {
    const context = this.context;
    if (!context)
      return;
    if (suggestion.isRaw) {
      context.editor.replaceRange(
        suggestion.snippet,
        context.start,
        context.end
      );
      return;
    }
    if (suggestion.isCustom) {
      const replacement2 = suggestion.snippet;
      if (!replacement2.includes("$1")) {
        context.editor.replaceRange(
          replacement2,
          context.start,
          context.end
        );
        return;
      }
      let firstTabstopOffset2 = Infinity;
      let cleanOffset2 = 0;
      let i2 = 0;
      while (i2 < replacement2.length) {
        const remaining = replacement2.substring(i2);
        const m = remaining.match(/^\$(\d+)/);
        if (m) {
          if (parseInt(m[1]) === 1 && cleanOffset2 < firstTabstopOffset2) {
            firstTabstopOffset2 = cleanOffset2;
          }
          i2 += m[0].length;
        } else {
          cleanOffset2++;
          i2++;
        }
      }
      const cleanReplacement2 = replacement2.replace(/\$\d+/g, "");
      context.editor.replaceRange(
        cleanReplacement2,
        context.start,
        context.end
      );
      context.editor.setCursor({
        line: context.start.line,
        ch: context.start.ch + firstTabstopOffset2
      });
      return;
    }
    const replacement = "\\" + suggestion.snippet;
    if (!replacement.includes("$1")) {
      context.editor.replaceRange(
        replacement,
        context.start,
        context.end
      );
      return;
    }
    let firstTabstopOffset = Infinity;
    let cleanOffset = 0;
    let i = 0;
    while (i < replacement.length) {
      const remaining = replacement.substring(i);
      const m = remaining.match(/^\$(\d+)/);
      if (m) {
        if (parseInt(m[1]) === 1 && cleanOffset < firstTabstopOffset) {
          firstTabstopOffset = cleanOffset;
        }
        i += m[0].length;
      } else {
        cleanOffset++;
        i++;
      }
    }
    const cleanReplacement = replacement.replace(/\$\d+/g, "");
    context.editor.replaceRange(
      cleanReplacement,
      context.start,
      context.end
    );
    context.editor.setCursor({
      line: context.start.line,
      ch: context.start.ch + firstTabstopOffset
    });
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  aiApiUrl: "https://api.openai.com/v1/chat/completions",
  aiApiKey: "",
  aiModel: "gpt-4o-mini",
  aiSystemPrompt: "",
  aiEnableThinking: false,
  customMappings: []
};

// src/i18n/en.ts
var en = {
  // Settings page
  "settings.title": "Easy LaTeX - AI Settings",
  "settings.apiUrl.name": "API URL",
  "settings.apiUrl.desc": "OpenAI-compatible API endpoint (fill up to /v1, /chat/completions will be appended automatically)",
  "settings.apiUrl.placeholder": "https://api.openai.com/v1/chat/completions",
  "settings.apiKey.name": "API Key",
  "settings.apiKey.desc": "Your API key",
  "settings.apiKey.placeholder": "sk-...",
  "settings.model.name": "Model",
  "settings.model.desc": "Model name (e.g., gpt-4o-mini, deepseek-chat)",
  "settings.model.placeholder": "gpt-4o-mini",
  "settings.systemPrompt.name": "System Prompt",
  "settings.systemPrompt.desc": "System prompt sent to the AI",
  "settings.systemPrompt.placeholder": "You are a LaTeX math formula converter...",
  "settings.thinking.name": "Enable Thinking Mode",
  "settings.thinking.desc": "Recommended to keep off. When enabled, the model will reason before outputting, which significantly increases LaTeX generation time. Only works with models that support thinking mode.",
  "settings.test.name": "Test Connection",
  "settings.test.desc": "Send a test request to verify API configuration",
  "settings.test.button": "Test",
  "settings.test.running": "Testing...",
  // Custom mappings
  "settings.customMappings.title": "Custom Keyword Mappings",
  "settings.customMappings.desc": "Add custom keyword-to-LaTeX snippet mappings. For Latin keywords, type \\keyword in math mode; for Chinese keywords, type directly. Use $1, $2 for cursor positions.",
  "settings.customMappings.keyword": "Keyword",
  "settings.customMappings.keywordPlaceholder": "div",
  "settings.customMappings.snippet": "LaTeX Snippet",
  "settings.customMappings.snippetPlaceholder": "\\frac{$1}{$2}",
  "settings.customMappings.add": "Add",
  "settings.customMappings.delete": "Delete",
  "settings.customMappings.emptyFields": "Keyword and snippet cannot be empty",
  // Notices
  "notice.generating": "Generating LaTeX...",
  "notice.generated": "Generated",
  "notice.success": "Connection successful: ",
  "notice.fail": "Connection failed: ",
  "notice.aiFail": "AI generation failed: ",
  // AI errors
  "ai.emptyResponse": "AI returned empty content",
  // Default AI system prompt
  "defaultPrompt": `You are a LaTeX math formula converter. Convert the user's math description into LaTeX code.
Rules:
1. Return only pure LaTeX code, no explanations
2. Do not wrap in markdown code blocks
3. Do not include $ or $$ delimiters
4. Maintain mathematical accuracy`
};
var en_default = en;

// src/i18n/zh-cn.ts
var zhCn = {
  // Settings page
  "settings.title": "Easy LaTeX - AI \u8BBE\u7F6E",
  "settings.apiUrl.name": "API URL",
  "settings.apiUrl.desc": "OpenAI \u517C\u5BB9\u683C\u5F0F\u7684 API \u5730\u5740\uFF08\u53EA\u9700\u586B\u5230 /v1\uFF0C\u4F1A\u81EA\u52A8\u8865\u5168 /chat/completions\uFF09",
  "settings.apiUrl.placeholder": "https://api.openai.com/v1/chat/completions",
  "settings.apiKey.name": "API Key",
  "settings.apiKey.desc": "\u4F60\u7684 API \u5BC6\u94A5",
  "settings.apiKey.placeholder": "sk-...",
  "settings.model.name": "Model",
  "settings.model.desc": "\u6A21\u578B\u540D\u79F0\uFF08\u5982 gpt-4o-mini\u3001deepseek-chat \u7B49\uFF09",
  "settings.model.placeholder": "gpt-4o-mini",
  "settings.systemPrompt.name": "System Prompt",
  "settings.systemPrompt.desc": "\u53D1\u9001\u7ED9 AI \u7684\u7CFB\u7EDF\u63D0\u793A\u8BCD",
  "settings.systemPrompt.placeholder": "\u4F60\u662F LaTeX \u6570\u5B66\u516C\u5F0F\u8F6C\u6362\u5668...",
  "settings.thinking.name": "\u542F\u7528\u601D\u8003\u6A21\u5F0F",
  "settings.thinking.desc": "\u5EFA\u8BAE\u4FDD\u6301\u5173\u95ED\uFF0C\u5F00\u542F\u540E\u6A21\u578B\u4F1A\u5148\u8FDB\u884C\u63A8\u7406\u518D\u8F93\u51FA\uFF0C\u751F\u6210 LaTeX \u7684\u65F6\u95F4\u4F1A\u660E\u663E\u53D8\u957F\u3002\u4EC5\u5BF9\u652F\u6301\u601D\u8003\u6A21\u5F0F\u7684\u6A21\u578B\u751F\u6548\u3002",
  "settings.test.name": "\u6D4B\u8BD5\u8FDE\u63A5",
  "settings.test.desc": "\u53D1\u9001\u6D4B\u8BD5\u8BF7\u6C42\u9A8C\u8BC1 API \u914D\u7F6E\u662F\u5426\u6B63\u786E",
  "settings.test.button": "\u6D4B\u8BD5",
  "settings.test.running": "\u6D4B\u8BD5\u4E2D...",
  // Custom mappings
  "settings.customMappings.title": "\u81EA\u5B9A\u4E49\u5173\u952E\u8BCD\u6620\u5C04",
  "settings.customMappings.desc": "\u6DFB\u52A0\u81EA\u5B9A\u4E49\u5173\u952E\u8BCD\u5230 LaTeX \u7247\u6BB5\u7684\u6620\u5C04\u3002\u62C9\u4E01\u5173\u952E\u8BCD\u5728\u6570\u5B66\u6A21\u5F0F\u4E0B\u8F93\u5165 \\keyword \u89E6\u53D1\uFF1B\u4E2D\u6587\u5173\u952E\u8BCD\u76F4\u63A5\u8F93\u5165\u89E6\u53D1\u3002\u7528 $1, $2 \u8868\u793A\u5149\u6807\u4F4D\u7F6E\u3002",
  "settings.customMappings.keyword": "\u5173\u952E\u8BCD",
  "settings.customMappings.keywordPlaceholder": "div",
  "settings.customMappings.snippet": "LaTeX \u7247\u6BB5",
  "settings.customMappings.snippetPlaceholder": "\\frac{$1}{$2}",
  "settings.customMappings.add": "\u6DFB\u52A0",
  "settings.customMappings.delete": "\u5220\u9664",
  "settings.customMappings.emptyFields": "\u5173\u952E\u8BCD\u548C\u7247\u6BB5\u4E0D\u80FD\u4E3A\u7A7A",
  // Notices
  "notice.generating": "\u6B63\u5728\u751F\u6210 LaTeX...",
  "notice.generated": "\u5DF2\u751F\u6210",
  "notice.success": "\u8FDE\u63A5\u6210\u529F: ",
  "notice.fail": "\u8FDE\u63A5\u5931\u8D25: ",
  "notice.aiFail": "AI \u751F\u6210\u5931\u8D25: ",
  // AI errors
  "ai.emptyResponse": "AI \u8FD4\u56DE\u5185\u5BB9\u4E3A\u7A7A",
  // Default AI system prompt
  "defaultPrompt": `\u4F60\u662F LaTeX \u6570\u5B66\u516C\u5F0F\u8F6C\u6362\u5668\u3002\u5C06\u7528\u6237\u7684\u6570\u5B66\u63CF\u8FF0\u8F6C\u6362\u4E3A LaTeX \u4EE3\u7801\u3002
\u89C4\u5219\uFF1A
1. \u53EA\u8FD4\u56DE\u7EAF LaTeX \u4EE3\u7801\uFF0C\u4E0D\u8981\u89E3\u91CA
2. \u4E0D\u8981\u7528 markdown \u4EE3\u7801\u5757\u5305\u88F9
3. \u4E0D\u8981\u5305\u542B $ \u6216 $$ \u5206\u9694\u7B26
4. \u4FDD\u6301\u6570\u5B66\u8BED\u4E49\u7684\u51C6\u786E\u6027`
};
var zh_cn_default = zhCn;

// src/i18n/index.ts
var translations = {
  en: en_default,
  zh: zh_cn_default,
  "zh-cn": zh_cn_default,
  "zh-tw": zh_cn_default,
  "zh-hans": zh_cn_default,
  "zh-hant": zh_cn_default
};
function getLocale() {
  var _a, _b, _c;
  return (_c = (_b = (_a = window.moment) == null ? void 0 : _a.locale) == null ? void 0 : _b.call(_a)) != null ? _c : "en";
}
function getTranslations() {
  var _a;
  const locale = getLocale();
  return (_a = translations[locale]) != null ? _a : translations["en"];
}
function t(key) {
  var _a, _b;
  return (_b = (_a = getTranslations()[key]) != null ? _a : en_default[key]) != null ? _b : key;
}

// src/ai.ts
var import_obsidian2 = require("obsidian");
function extractPromptText(editor, cursor) {
  const start = findMathZoneStart(editor, cursor);
  if (!start)
    return null;
  let text = "";
  if (start.line === cursor.line) {
    text = editor.getLine(start.line).substring(start.ch, cursor.ch);
  } else {
    text = editor.getLine(start.line).substring(start.ch);
    for (let i = start.line + 1; i < cursor.line; i++) {
      text += "\n" + editor.getLine(i);
    }
    text += "\n" + editor.getLine(cursor.line).substring(0, cursor.ch);
  }
  text = text.trim();
  if (!text)
    return null;
  return { text, start, end: cursor };
}
async function callAiApi(text, settings) {
  var _a, _b, _c;
  let apiUrl = settings.aiApiUrl.replace(/\/+$/, "");
  if (!apiUrl.includes("/chat/completions")) {
    apiUrl += "/chat/completions";
  }
  const body = {
    model: settings.aiModel,
    messages: [
      { role: "system", content: settings.aiSystemPrompt },
      { role: "user", content: text }
    ],
    temperature: 0.1
  };
  if (settings.aiEnableThinking) {
    body.enable_thinking = true;
  }
  const response = await (0, import_obsidian2.requestUrl)({
    url: apiUrl,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settings.aiApiKey}`
    },
    body: JSON.stringify(body)
  });
  const data = response.json;
  const content = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  if (!content)
    throw new Error(t("ai.emptyResponse"));
  return content.replace(/^```(?:latex|tex|math)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim();
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var LatexAutocompleteSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin, settings, onSave) {
    super(app, plugin);
    this.settings = settings;
    this.onSave = onSave;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName(t("settings.title")).setHeading();
    new import_obsidian3.Setting(containerEl).setName(t("settings.apiUrl.name")).setDesc(t("settings.apiUrl.desc")).addText(
      (text) => text.setPlaceholder(t("settings.apiUrl.placeholder")).setValue(this.settings.aiApiUrl).onChange(async (value) => {
        this.settings.aiApiUrl = value;
        await this.onSave();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("settings.apiKey.name")).setDesc(t("settings.apiKey.desc")).addText((text) => {
      text.setPlaceholder(t("settings.apiKey.placeholder")).setValue(this.settings.aiApiKey).onChange(async (value) => {
        this.settings.aiApiKey = value;
        await this.onSave();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian3.Setting(containerEl).setName(t("settings.model.name")).setDesc(t("settings.model.desc")).addText(
      (text) => text.setPlaceholder(t("settings.model.placeholder")).setValue(this.settings.aiModel).onChange(async (value) => {
        this.settings.aiModel = value;
        await this.onSave();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("settings.systemPrompt.name")).setDesc(t("settings.systemPrompt.desc")).addTextArea(
      (text) => text.setPlaceholder(t("settings.systemPrompt.placeholder")).setValue(this.settings.aiSystemPrompt).onChange(async (value) => {
        this.settings.aiSystemPrompt = value;
        await this.onSave();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("settings.thinking.name")).setDesc(t("settings.thinking.desc")).addToggle(
      (toggle) => toggle.setValue(this.settings.aiEnableThinking).onChange(async (value) => {
        this.settings.aiEnableThinking = value;
        await this.onSave();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("settings.test.name")).setDesc(t("settings.test.desc")).addButton(
      (btn) => btn.setButtonText(t("settings.test.button")).onClick(async () => {
        btn.setButtonText(t("settings.test.running"));
        btn.buttonEl.disabled = true;
        try {
          const result = await callAiApi("1+1\u7B49\u4E8E\u51E0", this.settings);
          new import_obsidian3.Notice(t("notice.success") + result, 4e3);
        } catch (err) {
          new import_obsidian3.Notice(t("notice.fail") + String(err), 5e3);
        }
        btn.setButtonText(t("settings.test.button"));
        btn.buttonEl.disabled = false;
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t("settings.customMappings.title")).setHeading();
    containerEl.createEl("p", {
      text: t("settings.customMappings.desc"),
      cls: "setting-item-description"
    });
    let newKeyword = "";
    let newSnippet = "";
    new import_obsidian3.Setting(containerEl).setName(t("settings.customMappings.keyword")).addText(
      (text) => text.setPlaceholder(t("settings.customMappings.keywordPlaceholder")).onChange((value) => {
        newKeyword = value;
      })
    ).addText(
      (text) => text.setPlaceholder(t("settings.customMappings.snippetPlaceholder")).onChange((value) => {
        newSnippet = value;
      })
    ).addButton(
      (btn) => btn.setButtonText(t("settings.customMappings.add")).onClick(async () => {
        const keyword = newKeyword.trim();
        const snippet = newSnippet.trim();
        if (!keyword || !snippet) {
          new import_obsidian3.Notice(t("settings.customMappings.emptyFields"));
          return;
        }
        this.settings.customMappings.push({ keyword, snippet });
        await this.onSave();
        this.display();
      })
    );
    for (let i = 0; i < this.settings.customMappings.length; i++) {
      const mapping = this.settings.customMappings[i];
      new import_obsidian3.Setting(containerEl).setName(mapping.keyword).setDesc(mapping.snippet).addButton(
        (btn) => btn.setButtonText("\xD7").onClick(async () => {
          this.settings.customMappings.splice(i, 1);
          await this.onSave();
          this.display();
        })
      );
    }
  }
};

// data/latex-commands.json
var latex_commands_default = [
  {
    command: "alpha",
    description: "Greek small letter alpha",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u963F\u5C14\u6CD5",
    snippet: "alpha",
    category: "greek_lower"
  },
  {
    command: "beta",
    description: "Greek small letter beta",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u8D1D\u5854",
    snippet: "beta",
    category: "greek_lower"
  },
  {
    command: "gamma",
    description: "Greek small letter gamma",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u4F3D\u9A6C",
    snippet: "gamma",
    category: "greek_lower"
  },
  {
    command: "delta",
    description: "Greek small letter delta",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5FB7\u5C14\u5854",
    snippet: "delta",
    category: "greek_lower"
  },
  {
    command: "epsilon",
    description: "Greek small letter epsilon",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u4F0A\u666E\u897F\u9F99",
    snippet: "epsilon",
    category: "greek_lower"
  },
  {
    command: "varepsilon",
    description: "Variant epsilon",
    descriptionZh: "\u53D8\u4F53\u4F0A\u666E\u897F\u9F99",
    snippet: "varepsilon",
    category: "greek_lower"
  },
  {
    command: "zeta",
    description: "Greek small letter zeta",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u6CFD\u5854",
    snippet: "zeta",
    category: "greek_lower"
  },
  {
    command: "eta",
    description: "Greek small letter eta",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u4F0A\u5854",
    snippet: "eta",
    category: "greek_lower"
  },
  {
    command: "theta",
    description: "Greek small letter theta",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u897F\u5854",
    snippet: "theta",
    category: "greek_lower"
  },
  {
    command: "vartheta",
    description: "Variant theta",
    descriptionZh: "\u53D8\u4F53\u897F\u5854",
    snippet: "vartheta",
    category: "greek_lower"
  },
  {
    command: "iota",
    description: "Greek small letter iota",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u7EA6\u5854",
    snippet: "iota",
    category: "greek_lower"
  },
  {
    command: "kappa",
    description: "Greek small letter kappa",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5361\u5E15",
    snippet: "kappa",
    category: "greek_lower"
  },
  {
    command: "lambda",
    description: "Greek small letter lambda",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u62C9\u59C6\u8FBE",
    snippet: "lambda",
    category: "greek_lower"
  },
  {
    command: "mu",
    description: "Greek small letter mu",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u7F2A",
    snippet: "mu",
    category: "greek_lower"
  },
  {
    command: "nu",
    description: "Greek small letter nu",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u7EBD",
    snippet: "nu",
    category: "greek_lower"
  },
  {
    command: "xi",
    description: "Greek small letter xi",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u514B\u897F",
    snippet: "xi",
    category: "greek_lower"
  },
  {
    command: "omicron",
    description: "Greek small letter omicron",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5965\u5BC6\u514B\u620E",
    snippet: "omicron",
    category: "greek_lower"
  },
  {
    command: "pi",
    description: "Greek small letter pi",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u6D3E",
    snippet: "pi",
    category: "greek_lower"
  },
  {
    command: "varpi",
    description: "Variant pi",
    descriptionZh: "\u53D8\u4F53\u6D3E",
    snippet: "varpi",
    category: "greek_lower"
  },
  {
    command: "rho",
    description: "Greek small letter rho",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u67D4",
    snippet: "rho",
    category: "greek_lower"
  },
  {
    command: "varrho",
    description: "Variant rho",
    descriptionZh: "\u53D8\u4F53\u67D4",
    snippet: "varrho",
    category: "greek_lower"
  },
  {
    command: "sigma",
    description: "Greek small letter sigma",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u897F\u683C\u9A6C",
    snippet: "sigma",
    category: "greek_lower"
  },
  {
    command: "varsigma",
    description: "Variant sigma",
    descriptionZh: "\u53D8\u4F53\u897F\u683C\u9A6C",
    snippet: "varsigma",
    category: "greek_lower"
  },
  {
    command: "tau",
    description: "Greek small letter tau",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u9676",
    snippet: "tau",
    category: "greek_lower"
  },
  {
    command: "upsilon",
    description: "Greek small letter upsilon",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5B87\u666E\u897F\u9F99",
    snippet: "upsilon",
    category: "greek_lower"
  },
  {
    command: "phi",
    description: "Greek small letter phi",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u6590",
    snippet: "phi",
    category: "greek_lower"
  },
  {
    command: "varphi",
    description: "Variant phi",
    descriptionZh: "\u53D8\u4F53\u6590",
    snippet: "varphi",
    category: "greek_lower"
  },
  {
    command: "chi",
    description: "Greek small letter chi",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5361\u4F0A",
    snippet: "chi",
    category: "greek_lower"
  },
  {
    command: "psi",
    description: "Greek small letter psi",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u666E\u897F",
    snippet: "psi",
    category: "greek_lower"
  },
  {
    command: "omega",
    description: "Greek small letter omega",
    descriptionZh: "\u5E0C\u814A\u5C0F\u5199\u5B57\u6BCD\u5965\u7C73\u4F3D",
    snippet: "omega",
    category: "greek_lower"
  },
  {
    command: "Gamma",
    description: "Greek capital letter Gamma",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u4F3D\u9A6C",
    snippet: "Gamma",
    category: "greek_upper"
  },
  {
    command: "Delta",
    description: "Greek capital letter Delta",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u5FB7\u5C14\u5854",
    snippet: "Delta",
    category: "greek_upper"
  },
  {
    command: "Theta",
    description: "Greek capital letter Theta",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u897F\u5854",
    snippet: "Theta",
    category: "greek_upper"
  },
  {
    command: "Lambda",
    description: "Greek capital letter Lambda",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u62C9\u59C6\u8FBE",
    snippet: "Lambda",
    category: "greek_upper"
  },
  {
    command: "Xi",
    description: "Greek capital letter Xi",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u514B\u897F",
    snippet: "Xi",
    category: "greek_upper"
  },
  {
    command: "Pi",
    description: "Greek capital letter Pi",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u6D3E",
    snippet: "Pi",
    category: "greek_upper"
  },
  {
    command: "Sigma",
    description: "Greek capital letter Sigma",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u897F\u683C\u9A6C",
    snippet: "Sigma",
    category: "greek_upper"
  },
  {
    command: "Upsilon",
    description: "Greek capital letter Upsilon",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u5B87\u666E\u897F\u9F99",
    snippet: "Upsilon",
    category: "greek_upper"
  },
  {
    command: "Phi",
    description: "Greek capital letter Phi",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u6590",
    snippet: "Phi",
    category: "greek_upper"
  },
  {
    command: "Psi",
    description: "Greek capital letter Psi",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u666E\u897F",
    snippet: "Psi",
    category: "greek_upper"
  },
  {
    command: "Omega",
    description: "Greek capital letter Omega",
    descriptionZh: "\u5E0C\u814A\u5927\u5199\u5B57\u6BCD\u5965\u7C73\u4F3D",
    snippet: "Omega",
    category: "greek_upper"
  },
  {
    command: "pm",
    description: "plus-minus sign",
    descriptionZh: "\u52A0\u51CF\u53F7",
    snippet: "pm",
    category: "operator"
  },
  {
    command: "mp",
    description: "minus-plus sign",
    descriptionZh: "\u51CF\u52A0\u53F7",
    snippet: "mp",
    category: "operator"
  },
  {
    command: "times",
    description: "multiplication sign",
    descriptionZh: "\u4E58\u53F7",
    snippet: "times",
    category: "operator"
  },
  {
    command: "div",
    description: "division sign",
    descriptionZh: "\u9664\u53F7",
    snippet: "div",
    category: "operator"
  },
  {
    command: "cdot",
    description: "centered dot",
    descriptionZh: "\u5C45\u4E2D\u70B9",
    snippet: "cdot",
    category: "operator"
  },
  {
    command: "ast",
    description: "asterisk operator",
    descriptionZh: "\u661F\u53F7\u8FD0\u7B97\u7B26",
    snippet: "ast",
    category: "operator"
  },
  {
    command: "star",
    description: "five-pointed star",
    descriptionZh: "\u4E94\u89D2\u661F",
    snippet: "star",
    category: "operator"
  },
  {
    command: "circ",
    description: "circle operator",
    descriptionZh: "\u5706\u5708\u8FD0\u7B97\u7B26",
    snippet: "circ",
    category: "operator"
  },
  {
    command: "bullet",
    description: "bullet operator",
    descriptionZh: "\u9879\u76EE\u7B26\u53F7\u8FD0\u7B97\u7B26",
    snippet: "bullet",
    category: "operator"
  },
  {
    command: "cap",
    description: "intersection",
    descriptionZh: "\u4EA4\u96C6",
    snippet: "cap",
    category: "operator"
  },
  {
    command: "cup",
    description: "union",
    descriptionZh: "\u5E76\u96C6",
    snippet: "cup",
    category: "operator"
  },
  {
    command: "setminus",
    description: "set minus",
    descriptionZh: "\u96C6\u5408\u5DEE",
    snippet: "setminus",
    category: "operator"
  },
  {
    command: "wr",
    description: "wreath product",
    descriptionZh: "\u5708\u79EF",
    snippet: "wr",
    category: "operator"
  },
  {
    command: "diamond",
    description: "diamond operator",
    descriptionZh: "\u83F1\u5F62\u8FD0\u7B97\u7B26",
    snippet: "diamond",
    category: "operator"
  },
  {
    command: "bigtriangleup",
    description: "big triangle up",
    descriptionZh: "\u5927\u4E0A\u4E09\u89D2",
    snippet: "bigtriangleup",
    category: "operator"
  },
  {
    command: "bigtriangledown",
    description: "big triangle down",
    descriptionZh: "\u5927\u4E0B\u4E09\u89D2",
    snippet: "bigtriangledown",
    category: "operator"
  },
  {
    command: "triangleleft",
    description: "left triangle",
    descriptionZh: "\u5DE6\u4E09\u89D2",
    snippet: "triangleleft",
    category: "operator"
  },
  {
    command: "triangleright",
    description: "right triangle",
    descriptionZh: "\u53F3\u4E09\u89D2",
    snippet: "triangleright",
    category: "operator"
  },
  {
    command: "oplus",
    description: "circled plus",
    descriptionZh: "\u5708\u52A0",
    snippet: "oplus",
    category: "operator"
  },
  {
    command: "ominus",
    description: "circled minus",
    descriptionZh: "\u5708\u51CF",
    snippet: "ominus",
    category: "operator"
  },
  {
    command: "otimes",
    description: "circled times",
    descriptionZh: "\u5708\u4E58",
    snippet: "otimes",
    category: "operator"
  },
  {
    command: "oslash",
    description: "circled slash",
    descriptionZh: "\u5708\u659C\u6760",
    snippet: "oslash",
    category: "operator"
  },
  {
    command: "odot",
    description: "circled dot",
    descriptionZh: "\u5708\u70B9",
    snippet: "odot",
    category: "operator"
  },
  {
    command: "bigcirc",
    description: "big circle",
    descriptionZh: "\u5927\u5706",
    snippet: "bigcirc",
    category: "operator"
  },
  {
    command: "dagger",
    description: "dagger",
    descriptionZh: "\u5251\u53F7",
    snippet: "dagger",
    category: "operator"
  },
  {
    command: "ddagger",
    description: "double dagger",
    descriptionZh: "\u53CC\u5251\u53F7",
    snippet: "ddagger",
    category: "operator"
  },
  {
    command: "amalg",
    description: "amalgamation",
    descriptionZh: "\u5408\u5E76\u8FD0\u7B97\u7B26",
    snippet: "amalg",
    category: "operator"
  },
  {
    command: "leq",
    description: "less than or equal",
    descriptionZh: "\u5C0F\u4E8E\u7B49\u4E8E",
    snippet: "leq",
    category: "relation"
  },
  {
    command: "le",
    description: "less than or equal",
    descriptionZh: "\u5C0F\u4E8E\u7B49\u4E8E",
    snippet: "le",
    category: "relation"
  },
  {
    command: "geq",
    description: "greater than or equal",
    descriptionZh: "\u5927\u4E8E\u7B49\u4E8E",
    snippet: "geq",
    category: "relation"
  },
  {
    command: "ge",
    description: "greater than or equal",
    descriptionZh: "\u5927\u4E8E\u7B49\u4E8E",
    snippet: "ge",
    category: "relation"
  },
  {
    command: "prec",
    description: "precedes",
    descriptionZh: "\u524D\u4E8E",
    snippet: "prec",
    category: "relation"
  },
  {
    command: "succ",
    description: "succeeds",
    descriptionZh: "\u540E\u4E8E",
    snippet: "succ",
    category: "relation"
  },
  {
    command: "preceq",
    description: "precedes or equal",
    descriptionZh: "\u524D\u4E8E\u7B49\u4E8E",
    snippet: "preceq",
    category: "relation"
  },
  {
    command: "succeq",
    description: "succeeds or equal",
    descriptionZh: "\u540E\u4E8E\u7B49\u4E8E",
    snippet: "succeq",
    category: "relation"
  },
  {
    command: "ll",
    description: "much less than",
    descriptionZh: "\u8FDC\u5C0F\u4E8E",
    snippet: "ll",
    category: "relation"
  },
  {
    command: "gg",
    description: "much greater than",
    descriptionZh: "\u8FDC\u5927\u4E8E",
    snippet: "gg",
    category: "relation"
  },
  {
    command: "subset",
    description: "subset",
    descriptionZh: "\u5B50\u96C6",
    snippet: "subset",
    category: "relation"
  },
  {
    command: "supset",
    description: "superset",
    descriptionZh: "\u8D85\u96C6",
    snippet: "supset",
    category: "relation"
  },
  {
    command: "subseteq",
    description: "subset or equal",
    descriptionZh: "\u5B50\u96C6\u7B49\u4E8E",
    snippet: "subseteq",
    category: "relation"
  },
  {
    command: "supseteq",
    description: "superset or equal",
    descriptionZh: "\u8D85\u96C6\u7B49\u4E8E",
    snippet: "supseteq",
    category: "relation"
  },
  {
    command: "sqsubset",
    description: "square subset",
    descriptionZh: "\u65B9\u5B50\u96C6",
    snippet: "sqsubset",
    category: "relation"
  },
  {
    command: "sqsupset",
    description: "square superset",
    descriptionZh: "\u65B9\u8D85\u96C6",
    snippet: "sqsupset",
    category: "relation"
  },
  {
    command: "sqsubseteq",
    description: "square subset or equal",
    descriptionZh: "\u65B9\u5B50\u96C6\u7B49\u4E8E",
    snippet: "sqsubseteq",
    category: "relation"
  },
  {
    command: "sqsupseteq",
    description: "square superset or equal",
    descriptionZh: "\u65B9\u8D85\u96C6\u7B49\u4E8E",
    snippet: "sqsupseteq",
    category: "relation"
  },
  {
    command: "sim",
    description: "similar",
    descriptionZh: "\u76F8\u4F3C",
    snippet: "sim",
    category: "relation"
  },
  {
    command: "simeq",
    description: "similar or equal",
    descriptionZh: "\u76F8\u4F3C\u7B49\u4E8E",
    snippet: "simeq",
    category: "relation"
  },
  {
    command: "approx",
    description: "approximately equal",
    descriptionZh: "\u7EA6\u7B49\u4E8E",
    snippet: "approx",
    category: "relation"
  },
  {
    command: "cong",
    description: "congruent",
    descriptionZh: "\u5168\u7B49",
    snippet: "cong",
    category: "relation"
  },
  {
    command: "equiv",
    description: "equivalent",
    descriptionZh: "\u7B49\u4EF7",
    snippet: "equiv",
    category: "relation"
  },
  {
    command: "doteq",
    description: "dot equal",
    descriptionZh: "\u70B9\u7B49\u4E8E",
    snippet: "doteq",
    category: "relation"
  },
  {
    command: "neq",
    description: "not equal",
    descriptionZh: "\u4E0D\u7B49\u4E8E",
    snippet: "neq",
    category: "relation"
  },
  {
    command: "ne",
    description: "not equal",
    descriptionZh: "\u4E0D\u7B49\u4E8E",
    snippet: "ne",
    category: "relation"
  },
  {
    command: "propto",
    description: "proportional",
    descriptionZh: "\u6B63\u6BD4\u4E8E",
    snippet: "propto",
    category: "relation"
  },
  {
    command: "models",
    description: "models",
    descriptionZh: "\u6A21\u578B",
    snippet: "models",
    category: "relation"
  },
  {
    command: "perp",
    description: "perpendicular",
    descriptionZh: "\u5782\u76F4",
    snippet: "perp",
    category: "relation"
  },
  {
    command: "mid",
    description: "divides",
    descriptionZh: "\u6574\u9664",
    snippet: "mid",
    category: "relation"
  },
  {
    command: "parallel",
    description: "parallel",
    descriptionZh: "\u5E73\u884C",
    snippet: "parallel",
    category: "relation"
  },
  {
    command: "asymp",
    description: "asymptotic",
    descriptionZh: "\u6E10\u8FD1",
    snippet: "asymp",
    category: "relation"
  },
  {
    command: "bowtie",
    description: "bowtie",
    descriptionZh: "\u8776\u5F62\u7ED3",
    snippet: "bowtie",
    category: "relation"
  },
  {
    command: "vdash",
    description: "turnstile",
    descriptionZh: "\u8BC1\u660Eturnstile",
    snippet: "vdash",
    category: "relation"
  },
  {
    command: "dashv",
    description: "reverse turnstile",
    descriptionZh: "\u53CD\u5411turnstile",
    snippet: "dashv",
    category: "relation"
  },
  {
    command: "in",
    description: "element of",
    descriptionZh: "\u5C5E\u4E8E",
    snippet: "in",
    category: "relation"
  },
  {
    command: "ni",
    description: "contains as member",
    descriptionZh: "\u5305\u542B\u5143\u7D20",
    snippet: "ni",
    category: "relation"
  },
  {
    command: "notin",
    description: "not an element of",
    descriptionZh: "\u4E0D\u5C5E\u4E8E",
    snippet: "notin",
    category: "relation"
  },
  {
    command: "vdots",
    description: "vertical dots",
    descriptionZh: "\u7AD6\u5411\u7701\u7565\u53F7",
    snippet: "vdots",
    category: "relation"
  },
  {
    command: "cdots",
    description: "centered dots",
    descriptionZh: "\u5C45\u4E2D\u7701\u7565\u53F7",
    snippet: "cdots",
    category: "relation"
  },
  {
    command: "ddots",
    description: "diagonal dots",
    descriptionZh: "\u5BF9\u89D2\u7701\u7565\u53F7",
    snippet: "ddots",
    category: "relation"
  },
  {
    command: "ldots",
    description: "low dots",
    descriptionZh: "\u5E95\u90E8\u7701\u7565\u53F7",
    snippet: "ldots",
    category: "relation"
  },
  {
    command: "leftarrow",
    description: "left arrow",
    descriptionZh: "\u5DE6\u7BAD\u5934",
    snippet: "leftarrow",
    category: "arrow"
  },
  {
    command: "Leftarrow",
    description: "double left arrow",
    descriptionZh: "\u53CC\u7EBF\u5DE6\u7BAD\u5934",
    snippet: "Leftarrow",
    category: "arrow"
  },
  {
    command: "rightarrow",
    description: "right arrow",
    descriptionZh: "\u53F3\u7BAD\u5934",
    snippet: "rightarrow",
    category: "arrow"
  },
  {
    command: "Rightarrow",
    description: "double right arrow",
    descriptionZh: "\u53CC\u7EBF\u53F3\u7BAD\u5934",
    snippet: "Rightarrow",
    category: "arrow"
  },
  {
    command: "leftrightarrow",
    description: "left-right arrow",
    descriptionZh: "\u5DE6\u53F3\u7BAD\u5934",
    snippet: "leftrightarrow",
    category: "arrow"
  },
  {
    command: "Leftrightarrow",
    description: "double left-right arrow",
    descriptionZh: "\u53CC\u7EBF\u5DE6\u53F3\u7BAD\u5934",
    snippet: "Leftrightarrow",
    category: "arrow"
  },
  {
    command: "uparrow",
    description: "up arrow",
    descriptionZh: "\u4E0A\u7BAD\u5934",
    snippet: "uparrow",
    category: "arrow"
  },
  {
    command: "Uparrow",
    description: "double up arrow",
    descriptionZh: "\u53CC\u7EBF\u4E0A\u7BAD\u5934",
    snippet: "Uparrow",
    category: "arrow"
  },
  {
    command: "downarrow",
    description: "down arrow",
    descriptionZh: "\u4E0B\u7BAD\u5934",
    snippet: "downarrow",
    category: "arrow"
  },
  {
    command: "Downarrow",
    description: "double down arrow",
    descriptionZh: "\u53CC\u7EBF\u4E0B\u7BAD\u5934",
    snippet: "Downarrow",
    category: "arrow"
  },
  {
    command: "updownarrow",
    description: "up-down arrow",
    descriptionZh: "\u4E0A\u4E0B\u7BAD\u5934",
    snippet: "updownarrow",
    category: "arrow"
  },
  {
    command: "Updownarrow",
    description: "double up-down arrow",
    descriptionZh: "\u53CC\u7EBF\u4E0A\u4E0B\u7BAD\u5934",
    snippet: "Updownarrow",
    category: "arrow"
  },
  {
    command: "longleftarrow",
    description: "long left arrow",
    descriptionZh: "\u957F\u5DE6\u7BAD\u5934",
    snippet: "longleftarrow",
    category: "arrow"
  },
  {
    command: "Longleftarrow",
    description: "long double left arrow",
    descriptionZh: "\u957F\u53CC\u7EBF\u5DE6\u7BAD\u5934",
    snippet: "Longleftarrow",
    category: "arrow"
  },
  {
    command: "longrightarrow",
    description: "long right arrow",
    descriptionZh: "\u957F\u53F3\u7BAD\u5934",
    snippet: "longrightarrow",
    category: "arrow"
  },
  {
    command: "Longrightarrow",
    description: "long double right arrow",
    descriptionZh: "\u957F\u53CC\u7EBF\u53F3\u7BAD\u5934",
    snippet: "Longrightarrow",
    category: "arrow"
  },
  {
    command: "longleftrightarrow",
    description: "long left-right arrow",
    descriptionZh: "\u957F\u5DE6\u53F3\u7BAD\u5934",
    snippet: "longleftrightarrow",
    category: "arrow"
  },
  {
    command: "Longleftrightarrow",
    description: "long double left-right arrow",
    descriptionZh: "\u957F\u53CC\u7EBF\u5DE6\u53F3\u7BAD\u5934",
    snippet: "Longleftrightarrow",
    category: "arrow"
  },
  {
    command: "mapsto",
    description: "maps to",
    descriptionZh: "\u6620\u5C04\u5230",
    snippet: "mapsto",
    category: "arrow"
  },
  {
    command: "longmapsto",
    description: "long maps to",
    descriptionZh: "\u957F\u6620\u5C04\u5230",
    snippet: "longmapsto",
    category: "arrow"
  },
  {
    command: "hookleftarrow",
    description: "hook left arrow",
    descriptionZh: "\u94A9\u5F62\u5DE6\u7BAD\u5934",
    snippet: "hookleftarrow",
    category: "arrow"
  },
  {
    command: "hookrightarrow",
    description: "hook right arrow",
    descriptionZh: "\u94A9\u5F62\u53F3\u7BAD\u5934",
    snippet: "hookrightarrow",
    category: "arrow"
  },
  {
    command: "leftharpoonup",
    description: "left harpoon up",
    descriptionZh: "\u5DE6\u4E0A\u9C7C\u53C9\u7BAD\u5934",
    snippet: "leftharpoonup",
    category: "arrow"
  },
  {
    command: "leftharpoondown",
    description: "left harpoon down",
    descriptionZh: "\u5DE6\u4E0B\u9C7C\u53C9\u7BAD\u5934",
    snippet: "leftharpoondown",
    category: "arrow"
  },
  {
    command: "rightharpoonup",
    description: "right harpoon up",
    descriptionZh: "\u53F3\u4E0A\u9C7C\u53C9\u7BAD\u5934",
    snippet: "rightharpoonup",
    category: "arrow"
  },
  {
    command: "rightharpoondown",
    description: "right harpoon down",
    descriptionZh: "\u53F3\u4E0B\u9C7C\u53C9\u7BAD\u5934",
    snippet: "rightharpoondown",
    category: "arrow"
  },
  {
    command: "nearrow",
    description: "north-east arrow",
    descriptionZh: "\u4E1C\u5317\u7BAD\u5934",
    snippet: "nearrow",
    category: "arrow"
  },
  {
    command: "searrow",
    description: "south-east arrow",
    descriptionZh: "\u4E1C\u5357\u7BAD\u5934",
    snippet: "searrow",
    category: "arrow"
  },
  {
    command: "swarrow",
    description: "south-west arrow",
    descriptionZh: "\u897F\u5357\u7BAD\u5934",
    snippet: "swarrow",
    category: "arrow"
  },
  {
    command: "nwarrow",
    description: "north-west arrow",
    descriptionZh: "\u897F\u5317\u7BAD\u5934",
    snippet: "nwarrow",
    category: "arrow"
  },
  {
    command: "frac",
    description: "fraction",
    descriptionZh: "\u5206\u6570",
    snippet: "frac{$1}{$2}",
    category: "construction"
  },
  {
    command: "dfrac",
    description: "display fraction",
    descriptionZh: "\u663E\u793A\u5206\u6570",
    snippet: "dfrac{$1}{$2}",
    category: "construction"
  },
  {
    command: "tfrac",
    description: "text fraction",
    descriptionZh: "\u6587\u672C\u5206\u6570",
    snippet: "tfrac{$1}{$2}",
    category: "construction"
  },
  {
    command: "sqrt",
    description: "square root",
    descriptionZh: "\u5E73\u65B9\u6839",
    snippet: "sqrt{$1}",
    category: "construction"
  },
  {
    command: "sum",
    description: "summation",
    descriptionZh: "\u6C42\u548C",
    snippet: "sum",
    category: "construction"
  },
  {
    command: "prod",
    description: "product",
    descriptionZh: "\u8FDE\u4E58",
    snippet: "prod",
    category: "construction"
  },
  {
    command: "coprod",
    description: "coproduct",
    descriptionZh: "\u4F59\u79EF",
    snippet: "coprod",
    category: "construction"
  },
  {
    command: "int",
    description: "integral",
    descriptionZh: "\u79EF\u5206",
    snippet: "int",
    category: "construction"
  },
  {
    command: "iint",
    description: "double integral",
    descriptionZh: "\u4E8C\u91CD\u79EF\u5206",
    snippet: "iint",
    category: "construction"
  },
  {
    command: "iiint",
    description: "triple integral",
    descriptionZh: "\u4E09\u91CD\u79EF\u5206",
    snippet: "iiint",
    category: "construction"
  },
  {
    command: "oint",
    description: "contour integral",
    descriptionZh: "\u73AF\u8DEF\u79EF\u5206",
    snippet: "oint",
    category: "construction"
  },
  {
    command: "bigint",
    description: "big integral",
    descriptionZh: "\u5927\u79EF\u5206\u53F7",
    snippet: "bigint",
    category: "construction"
  },
  {
    command: "bigsum",
    description: "big summation",
    descriptionZh: "\u5927\u6C42\u548C\u53F7",
    snippet: "bigsum",
    category: "construction"
  },
  {
    command: "lim",
    description: "limit",
    descriptionZh: "\u6781\u9650",
    snippet: "lim",
    category: "construction"
  },
  {
    command: "sup",
    description: "supremum",
    descriptionZh: "\u4E0A\u786E\u754C",
    snippet: "sup",
    category: "construction"
  },
  {
    command: "inf",
    description: "infimum",
    descriptionZh: "\u4E0B\u786E\u754C",
    snippet: "inf",
    category: "construction"
  },
  {
    command: "max",
    description: "maximum",
    descriptionZh: "\u6700\u5927\u503C",
    snippet: "max",
    category: "construction"
  },
  {
    command: "min",
    description: "minimum",
    descriptionZh: "\u6700\u5C0F\u503C",
    snippet: "min",
    category: "construction"
  },
  {
    command: "binom",
    description: "binomial coefficient",
    descriptionZh: "\u4E8C\u9879\u5F0F\u7CFB\u6570",
    snippet: "binom{$1}{$2}",
    category: "construction"
  },
  {
    command: "tbinom",
    description: "text binomial",
    descriptionZh: "\u6587\u672C\u4E8C\u9879\u5F0F",
    snippet: "tbinom{$1}{$2}",
    category: "construction"
  },
  {
    command: "dbinom",
    description: "display binomial",
    descriptionZh: "\u663E\u793A\u4E8C\u9879\u5F0F",
    snippet: "dbinom{$1}{$2}",
    category: "construction"
  },
  {
    command: "overline",
    description: "overline",
    descriptionZh: "\u4E0A\u5212\u7EBF",
    snippet: "overline{$1}",
    category: "construction"
  },
  {
    command: "underline",
    description: "underline",
    descriptionZh: "\u4E0B\u5212\u7EBF",
    snippet: "underline{$1}",
    category: "construction"
  },
  {
    command: "overbrace",
    description: "overbrace",
    descriptionZh: "\u4E0A\u82B1\u62EC\u53F7",
    snippet: "overbrace{$1}",
    category: "construction"
  },
  {
    command: "underbrace",
    description: "underbrace",
    descriptionZh: "\u4E0B\u82B1\u62EC\u53F7",
    snippet: "underbrace{$1}",
    category: "construction"
  },
  {
    command: "stackrel",
    description: "stack relation",
    descriptionZh: "\u5806\u53E0\u5173\u7CFB",
    snippet: "stackrel{$1}{$2}",
    category: "construction"
  },
  {
    command: "left",
    description: "left delimiter",
    descriptionZh: "\u5DE6\u5B9A\u754C\u7B26",
    snippet: "left$1",
    category: "delimiter"
  },
  {
    command: "right",
    description: "right delimiter",
    descriptionZh: "\u53F3\u5B9A\u754C\u7B26",
    snippet: "right$1",
    category: "delimiter"
  },
  {
    command: "langle",
    description: "left angle bracket",
    descriptionZh: "\u5DE6\u5C16\u62EC\u53F7",
    snippet: "langle",
    category: "delimiter"
  },
  {
    command: "rangle",
    description: "right angle bracket",
    descriptionZh: "\u53F3\u5C16\u62EC\u53F7",
    snippet: "rangle",
    category: "delimiter"
  },
  {
    command: "lceil",
    description: "left ceiling",
    descriptionZh: "\u5DE6\u5411\u4E0A\u53D6\u6574\u7B26",
    snippet: "lceil",
    category: "delimiter"
  },
  {
    command: "rceil",
    description: "right ceiling",
    descriptionZh: "\u53F3\u5411\u4E0A\u53D6\u6574\u7B26",
    snippet: "rceil",
    category: "delimiter"
  },
  {
    command: "lfloor",
    description: "left floor",
    descriptionZh: "\u5DE6\u5411\u4E0B\u53D6\u6574\u7B26",
    snippet: "lfloor",
    category: "delimiter"
  },
  {
    command: "rfloor",
    description: "right floor",
    descriptionZh: "\u53F3\u5411\u4E0B\u53D6\u6574\u7B26",
    snippet: "rfloor",
    category: "delimiter"
  },
  {
    command: "lvert",
    description: "left vertical bar",
    descriptionZh: "\u5DE6\u7AD6\u7EBF",
    snippet: "lvert",
    category: "delimiter"
  },
  {
    command: "rvert",
    description: "right vertical bar",
    descriptionZh: "\u53F3\u7AD6\u7EBF",
    snippet: "rvert",
    category: "delimiter"
  },
  {
    command: "hat",
    description: "hat accent",
    descriptionZh: "\u5E3D\u5B50\u91CD\u97F3",
    snippet: "hat{$1}",
    category: "accent"
  },
  {
    command: "check",
    description: "check accent",
    descriptionZh: "\u52FE\u53F7\u91CD\u97F3",
    snippet: "check{$1}",
    category: "accent"
  },
  {
    command: "breve",
    description: "breve accent",
    descriptionZh: "\u77ED\u97F3\u91CD\u97F3",
    snippet: "breve{$1}",
    category: "accent"
  },
  {
    command: "acute",
    description: "acute accent",
    descriptionZh: "\u5C16\u97F3\u91CD\u97F3",
    snippet: "acute{$1}",
    category: "accent"
  },
  {
    command: "grave",
    description: "grave accent",
    descriptionZh: "\u91CD\u97F3\u91CD\u97F3",
    snippet: "grave{$1}",
    category: "accent"
  },
  {
    command: "tilde",
    description: "tilde accent",
    descriptionZh: "\u6CE2\u6D6A\u91CD\u97F3",
    snippet: "tilde{$1}",
    category: "accent"
  },
  {
    command: "bar",
    description: "bar accent",
    descriptionZh: "\u6A2A\u7EBF\u91CD\u97F3",
    snippet: "bar{$1}",
    category: "accent"
  },
  {
    command: "vec",
    description: "vector accent",
    descriptionZh: "\u5411\u91CF\u91CD\u97F3",
    snippet: "vec{$1}",
    category: "accent"
  },
  {
    command: "dot",
    description: "dot accent",
    descriptionZh: "\u70B9\u91CD\u97F3",
    snippet: "dot{$1}",
    category: "accent"
  },
  {
    command: "ddot",
    description: "double dot accent",
    descriptionZh: "\u53CC\u70B9\u91CD\u97F3",
    snippet: "ddot{$1}",
    category: "accent"
  },
  {
    command: "widehat",
    description: "wide hat accent",
    descriptionZh: "\u5BBD\u5E3D\u5B50\u91CD\u97F3",
    snippet: "widehat{$1}",
    category: "accent"
  },
  {
    command: "widetilde",
    description: "wide tilde accent",
    descriptionZh: "\u5BBD\u6CE2\u6D6A\u91CD\u97F3",
    snippet: "widetilde{$1}",
    category: "accent"
  },
  {
    command: "overrightarrow",
    description: "right arrow over",
    descriptionZh: "\u4E0A\u65B9\u53F3\u7BAD\u5934",
    snippet: "overrightarrow{$1}",
    category: "accent"
  },
  {
    command: "overleftarrow",
    description: "left arrow over",
    descriptionZh: "\u4E0A\u65B9\u5DE6\u7BAD\u5934",
    snippet: "overleftarrow{$1}",
    category: "accent"
  },
  {
    command: "mathring",
    description: "ring accent",
    descriptionZh: "\u5706\u73AF\u91CD\u97F3",
    snippet: "mathring{$1}",
    category: "accent"
  },
  {
    command: "sin",
    description: "sine",
    descriptionZh: "\u6B63\u5F26",
    snippet: "sin",
    category: "function"
  },
  {
    command: "cos",
    description: "cosine",
    descriptionZh: "\u4F59\u5F26",
    snippet: "cos",
    category: "function"
  },
  {
    command: "tan",
    description: "tangent",
    descriptionZh: "\u6B63\u5207",
    snippet: "tan",
    category: "function"
  },
  {
    command: "cot",
    description: "cotangent",
    descriptionZh: "\u4F59\u5207",
    snippet: "cot",
    category: "function"
  },
  {
    command: "sec",
    description: "secant",
    descriptionZh: "\u6B63\u5272",
    snippet: "sec",
    category: "function"
  },
  {
    command: "csc",
    description: "cosecant",
    descriptionZh: "\u4F59\u5272",
    snippet: "csc",
    category: "function"
  },
  {
    command: "arcsin",
    description: "arcsine",
    descriptionZh: "\u53CD\u6B63\u5F26",
    snippet: "arcsin",
    category: "function"
  },
  {
    command: "arccos",
    description: "arccosine",
    descriptionZh: "\u53CD\u4F59\u5F26",
    snippet: "arccos",
    category: "function"
  },
  {
    command: "arctan",
    description: "arctangent",
    descriptionZh: "\u53CD\u6B63\u5207",
    snippet: "arctan",
    category: "function"
  },
  {
    command: "sinh",
    description: "hyperbolic sine",
    descriptionZh: "\u53CC\u66F2\u6B63\u5F26",
    snippet: "sinh",
    category: "function"
  },
  {
    command: "cosh",
    description: "hyperbolic cosine",
    descriptionZh: "\u53CC\u66F2\u4F59\u5F26",
    snippet: "cosh",
    category: "function"
  },
  {
    command: "tanh",
    description: "hyperbolic tangent",
    descriptionZh: "\u53CC\u66F2\u6B63\u5207",
    snippet: "tanh",
    category: "function"
  },
  {
    command: "log",
    description: "logarithm",
    descriptionZh: "\u5BF9\u6570",
    snippet: "log",
    category: "function"
  },
  {
    command: "ln",
    description: "natural logarithm",
    descriptionZh: "\u81EA\u7136\u5BF9\u6570",
    snippet: "ln",
    category: "function"
  },
  {
    command: "exp",
    description: "exponential",
    descriptionZh: "\u6307\u6570",
    snippet: "exp",
    category: "function"
  },
  {
    command: "det",
    description: "determinant",
    descriptionZh: "\u884C\u5217\u5F0F",
    snippet: "det",
    category: "function"
  },
  {
    command: "dim",
    description: "dimension",
    descriptionZh: "\u7EF4\u6570",
    snippet: "dim",
    category: "function"
  },
  {
    command: "ker",
    description: "kernel",
    descriptionZh: "\u6838",
    snippet: "ker",
    category: "function"
  },
  {
    command: "deg",
    description: "degree",
    descriptionZh: "\u5EA6\u6570",
    snippet: "deg",
    category: "function"
  },
  {
    command: "gcd",
    description: "greatest common divisor",
    descriptionZh: "\u6700\u5927\u516C\u7EA6\u6570",
    snippet: "gcd",
    category: "function"
  },
  {
    command: "arg",
    description: "argument",
    descriptionZh: "\u8F90\u89D2",
    snippet: "arg",
    category: "function"
  },
  {
    command: "limsup",
    description: "limit superior",
    descriptionZh: "\u4E0A\u6781\u9650",
    snippet: "limsup",
    category: "function"
  },
  {
    command: "liminf",
    description: "limit inferior",
    descriptionZh: "\u4E0B\u6781\u9650",
    snippet: "liminf",
    category: "function"
  },
  {
    command: "Pr",
    description: "probability",
    descriptionZh: "\u6982\u7387",
    snippet: "Pr",
    category: "function"
  },
  {
    command: "bmod",
    description: "binary modulo",
    descriptionZh: "\u4E8C\u5143\u53D6\u6A21",
    snippet: "bmod",
    category: "function"
  },
  {
    command: "pmod",
    description: "parenthetical modulo",
    descriptionZh: "\u5706\u62EC\u53F7\u53D6\u6A21",
    snippet: "pmod{$1}",
    category: "function"
  },
  {
    command: "infty",
    description: "infinity",
    descriptionZh: "\u65E0\u7A77\u5927",
    snippet: "infty",
    category: "symbol"
  },
  {
    command: "partial",
    description: "partial derivative",
    descriptionZh: "\u504F\u5BFC\u6570",
    snippet: "partial",
    category: "symbol"
  },
  {
    command: "nabla",
    description: "nabla",
    descriptionZh: "\u68AF\u5EA6\u7B97\u5B50",
    snippet: "nabla",
    category: "symbol"
  },
  {
    command: "forall",
    description: "for all",
    descriptionZh: "\u4EFB\u610F",
    snippet: "forall",
    category: "symbol"
  },
  {
    command: "exists",
    description: "exists",
    descriptionZh: "\u5B58\u5728",
    snippet: "exists",
    category: "symbol"
  },
  {
    command: "nexists",
    description: "not exists",
    descriptionZh: "\u4E0D\u5B58\u5728",
    snippet: "nexists",
    category: "symbol"
  },
  {
    command: "neg",
    description: "negation",
    descriptionZh: "\u5426\u5B9A",
    snippet: "neg",
    category: "symbol"
  },
  {
    command: "lnot",
    description: "logical not",
    descriptionZh: "\u903B\u8F91\u975E",
    snippet: "lnot",
    category: "symbol"
  },
  {
    command: "land",
    description: "logical and",
    descriptionZh: "\u903B\u8F91\u4E0E",
    snippet: "land",
    category: "symbol"
  },
  {
    command: "lor",
    description: "logical or",
    descriptionZh: "\u903B\u8F91\u6216",
    snippet: "lor",
    category: "symbol"
  },
  {
    command: "top",
    description: "top",
    descriptionZh: "\u9876",
    snippet: "top",
    category: "symbol"
  },
  {
    command: "bot",
    description: "bottom",
    descriptionZh: "\u5E95",
    snippet: "bot",
    category: "symbol"
  },
  {
    command: "emptyset",
    description: "empty set",
    descriptionZh: "\u7A7A\u96C6",
    snippet: "emptyset",
    category: "symbol"
  },
  {
    command: "varnothing",
    description: "variant empty set",
    descriptionZh: "\u53D8\u4F53\u7A7A\u96C6",
    snippet: "varnothing",
    category: "symbol"
  },
  {
    command: "aleph",
    description: "aleph",
    descriptionZh: "\u963F\u5217\u592B",
    snippet: "aleph",
    category: "symbol"
  },
  {
    command: "beth",
    description: "beth",
    descriptionZh: "\u8D1D\u65AF",
    snippet: "beth",
    category: "symbol"
  },
  {
    command: "hbar",
    description: "h-bar",
    descriptionZh: "\u7EA6\u5316\u666E\u6717\u514B\u5E38\u6570",
    snippet: "hbar",
    category: "symbol"
  },
  {
    command: "ell",
    description: "script l",
    descriptionZh: "\u82B1\u4F53l",
    snippet: "ell",
    category: "symbol"
  },
  {
    command: "imath",
    description: "dotless i",
    descriptionZh: "\u65E0\u70B9i",
    snippet: "imath",
    category: "symbol"
  },
  {
    command: "jmath",
    description: "dotless j",
    descriptionZh: "\u65E0\u70B9j",
    snippet: "jmath",
    category: "symbol"
  },
  {
    command: "Re",
    description: "real part",
    descriptionZh: "\u5B9E\u90E8",
    snippet: "Re",
    category: "symbol"
  },
  {
    command: "Im",
    description: "imaginary part",
    descriptionZh: "\u865A\u90E8",
    snippet: "Im",
    category: "symbol"
  },
  {
    command: "wp",
    description: "Weierstrass p",
    descriptionZh: "\u9B4F\u5C14\u65AF\u7279\u62C9\u65AFp",
    snippet: "wp",
    category: "symbol"
  },
  {
    command: "mho",
    description: "mho",
    descriptionZh: "\u59C6\u6B27",
    snippet: "mho",
    category: "symbol"
  },
  {
    command: "Box",
    description: "box",
    descriptionZh: "\u65B9\u6846",
    snippet: "Box",
    category: "symbol"
  },
  {
    command: "Diamond",
    description: "diamond",
    descriptionZh: "\u83F1\u5F62",
    snippet: "Diamond",
    category: "symbol"
  },
  {
    command: "clubsuit",
    description: "club suit",
    descriptionZh: "\u6885\u82B1",
    snippet: "clubsuit",
    category: "symbol"
  },
  {
    command: "diamondsuit",
    description: "diamond suit",
    descriptionZh: "\u65B9\u5757",
    snippet: "diamondsuit",
    category: "symbol"
  },
  {
    command: "heartsuit",
    description: "heart suit",
    descriptionZh: "\u7EA2\u5FC3",
    snippet: "heartsuit",
    category: "symbol"
  },
  {
    command: "spadesuit",
    description: "spade suit",
    descriptionZh: "\u9ED1\u6843",
    snippet: "spadesuit",
    category: "symbol"
  },
  {
    command: "flat",
    description: "flat",
    descriptionZh: "\u964D\u53F7",
    snippet: "flat",
    category: "symbol"
  },
  {
    command: "natural",
    description: "natural",
    descriptionZh: "\u8FD8\u539F\u53F7",
    snippet: "natural",
    category: "symbol"
  },
  {
    command: "sharp",
    description: "sharp",
    descriptionZh: "\u5347\u53F7",
    snippet: "sharp",
    category: "symbol"
  },
  {
    command: "surd",
    description: "radical sign",
    descriptionZh: "\u6839\u53F7",
    snippet: "surd",
    category: "symbol"
  },
  {
    command: "triangle",
    description: "triangle",
    descriptionZh: "\u4E09\u89D2\u5F62",
    snippet: "triangle",
    category: "symbol"
  }
];

// main.ts
var LEGACY_DEFAULT_PROMPT = `\u4F60\u662F LaTeX \u6570\u5B66\u516C\u5F0F\u8F6C\u6362\u5668\u3002\u5C06\u7528\u6237\u7684\u6570\u5B66\u63CF\u8FF0\u8F6C\u6362\u4E3A LaTeX \u4EE3\u7801\u3002
	\u89C4\u5219\uFF1A
	1. \u53EA\u8FD4\u56DE\u7EAF LaTeX \u4EE3\u7801\uFF0C\u4E0D\u8981\u89E3\u91CA
	2. \u4E0D\u8981\u7528 markdown \u4EE3\u7801\u5757\u5305\u88F9
	3. \u4E0D\u8981\u5305\u542B $ \u6216 $$ \u5206\u9694\u7B26
	4. \u4FDD\u6301\u6570\u5B66\u8BED\u4E49\u7684\u51C6\u786E\u6027`;
var LatexAutocompletePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const commands = latex_commands_default;
    this.registerEditorSuggest(
      new LatexSuggest(this.app, commands, LANG_REGISTRY, () => this.settings)
    );
    const tabHandler = (evt) => {
      if (evt.key === "Tab" && !evt.ctrlKey && !evt.altKey && !evt.metaKey) {
        if (this.handleTab()) {
          evt.preventDefault();
          evt.stopPropagation();
        }
      }
    };
    const doc = window.activeDocument;
    doc.addEventListener("keydown", tabHandler, true);
    this.register(() => doc.removeEventListener("keydown", tabHandler, true));
    this.addSettingTab(
      new LatexAutocompleteSettingTab(
        this.app,
        this,
        this.settings,
        () => this.saveSettings()
      )
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!this.settings.aiSystemPrompt || this.settings.aiSystemPrompt === LEGACY_DEFAULT_PROMPT) {
      this.settings.aiSystemPrompt = t("defaultPrompt");
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  handleTab() {
    var _a;
    if (!this.settings.aiApiKey)
      return false;
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (!editor)
      return false;
    const cursor = editor.getCursor("head");
    if (!isInMathContext(editor, cursor))
      return false;
    const result = extractPromptText(editor, cursor);
    if (!result)
      return false;
    const notice = new import_obsidian4.Notice(t("notice.generating"), 0);
    callAiApi(result.text, this.settings).then((latex) => {
      editor.replaceRange(latex, result.start, result.end);
      editor.setCursor({
        line: result.start.line,
        ch: result.start.ch + latex.length
      });
      notice.hide();
      new import_obsidian4.Notice(t("notice.generated"), 2e3);
    }).catch((err) => {
      notice.hide();
      new import_obsidian4.Notice(t("notice.aiFail") + String(err), 5e3);
    });
    return true;
  }
};
